# values.yaml
executor: "CeleryExecutor"

config:
  core:
    load_examples: "False"
    load_default_connections: "False"

  kubernetes:
    namespace: "airflow"

  webserver:
    defaultUser:
      username: "admin"
      password: "admin"
      role: "Admin"
      email: "admin@example.com"

postgresql:
  enabled: true
  postgresqlUsername: "airflow"
  postgresqlPassword: "airflow"

redis:
  enabled: true



# helm install airflow apache-airflow/airflow --namespace airflow --values values.yaml --debug
# kubectl port-forward svc/airflow-webserver 8080:8080 --namespace airflow